[package]
name = "my_blockchain_project"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
substrate = "0.1.0"
tokio = { version = "1.45.1", features = ["full"] }
